#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
#[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    #colorscheme = "gruvbox"
    #colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    #enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    #statusline_separator = "arrow"
    #statusline_inactive_separator = "arrow"
    #buffer_index_type = 4
    #enable_tabline_filetype_icon = true
    #enable_statusline_mode = false

# Enable autocomplete layer

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "coc"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "checkers"
  show_cursor_error = false

[[layers]]
  name = "chinese"
  
[[layers]]
  name = "colorscheme"

[[layers]]
  name = "core"

  filetree_show_hidden = true
[[layers]]
  name = "cscope"

[[layers]]
  name = "debug"

[[layers]]
  name = "default"

[[layers]]
	name = "denite"

[[layers]]
  name = "foldsearch"

[[layers]]
  name = "format"
  enable = false

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "gtags"
  gtagslabel = "pygments"

[[layers]]
  name = "lang#c"

  enable_clang_syntax_highlight = true
  
  clang_executable = "/usr/bin/clang"
  [layer.clang_std]
    c = "c11"
#    cpp = "c++17"
    objc = "c11"
#    objcpp = "c++17"

[[layers]]
  name = "lang#extra"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "java"

[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true

[[layers]]
  name = "lang#lua"

[[layers]]
  name = "lang#perl"

[[layers]]
  name = "php"

[[layers]]
  name = "lang#powershell"

[[layers]]
  name = "lang#python"
  enable_typeinfo = true

  python_file_head = [
      '#!/usr/bin/env python',
      '# -*- coding: utf-8 -*-',
      '',
      ''
  ]

[[layers]]
  name = "lang#ruby"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#typesript"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#vue"

[[layers]]
  name = "lang#xml"

[[layers]]
  name = "leaderf"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "sudo"

[[layers]]
  name = "test"

[[layers]]
  name = "tmux"
  tmux_navigator_modifier = "alt"

[[layers]]
  name = "tools"

[[layers]]
  name = "ui"

[[layers]]
  name = "unite"

  enable = false

[[layers]]
  name = "lsp"
  filetypes = [
     "c",
     "cpp",
     "php",
     "ruby",
     "java"
  ]

  [layers.override_cmd]
    c = ["clangd"]
    php = ["psalm-language-server"]
    ruby = ["solargraph", "stdio"]
    java = [
    	"java",
    	"-Declipse.application=org.eclipse.jdt.ls.core.id1",
    	"-Dosgi.bundles.defaultStartLevel=4",
    	"-Declipse.product=org.eclipse.jdt.ls.core.product",
    	"-Dlog.protocol=true",
    	"-Dlog.level=NONE",
    	"-noverify",
    	"-Xmx1G",
    	"-jar",
      "~/.java/jdt/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar"
    	"-configuration",
      "~/.java/jdt/config_linux"
    	"-data",
    	"~/.java/lsp" 
    ]

[options]
  bootstrap_before = "myspacevim#before"
  bootstrap_after = "myspacevim#after"

  colorscheme = "NeoSolarized"
  colorscheme_bg = "dark"
  enable_guicolors = true

  statusline_separator = "nil"
  statusline_inactive_separator = "bar"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = true
  
  vim_help_language = "cn"

  enable_neomake = false
  enable_ale = true
  snippet_engine = "ultisnips"
  filemanager = "nerdtree"
  filetree_direction = "left"

  layer_lang_java_formatter = '~/.java/format/google-java-format-1.8.jar'
